using System.ComponentModel;
using System.Globalization;

namespace BtChat;

public sealed class Loc : INotifyPropertyChanged
{
    public static Loc Instance { get; } = new();

    static readonly Dictionary<string, (string Fa, string En)> table = new()
    {
        ["lang"] = ("English", "فارسی"),
        ["mode"] = ("نوع اتصال", "Connection type"),
        ["edit"] = ("ویرایش", "Edit"),
        ["edited"] = ("ویرایش‌شده", "edited"),
        ["editTitle"] = ("ویرایش پیام", "Edit message"),
        ["editNeedsConnection"] = ("برای ویرایش پیام باید به همین دستگاه وصل باشید تا تغییر برای او هم اعمال شود", "Connect to this device to edit the message, so the change reaches it too"),
        ["copyText"] = ("کپی متن", "Copy text"),
        ["openFile"] = ("باز کردن فایل", "Open file"),
        ["openFolder"] = ("رفتن به پوشه", "Go to folder"),
        ["savedIn"] = ("فایل در این پوشه ذخیره شده:", "Saved in:"),
        ["noApp"] = ("برنامه‌ای برای باز کردن این فایل پیدا نشد", "No app found to open this file"),
        ["share"] = ("اشتراک‌گذاری", "Share"),
        ["cancel"] = ("انصراف", "Cancel"),
        ["clearHistory"] = ("پاک کردن تاریخچه چت", "Clear chat history"),
        ["clearHistoryAsk"] = ("همه پیام‌ها از لیست چت پاک شوند؟ فایل‌های ذخیره‌شده روی دستگاه پاک نمی‌شوند.", "Remove all messages from the chat? Files saved on this device are not deleted."),
        ["deleteMessage"] = ("حذف پیام", "Delete message"),
        ["deleteFile"] = ("حذف فایل", "Delete file"),
        ["deleteFileAsk"] = ("این فایل از حافظه دستگاه هم پاک می‌شود. ادامه می‌دهید؟", "This file will also be deleted from this device. Continue?"),
        ["deleteFileFailed"] = ("حذف فایل از حافظه انجام نشد (شاید قبلاً پاک شده باشد). پیام از چت حذف شد.", "Could not delete the file from storage (it may already be gone). The message was removed from the chat."),
        ["delete"] = ("حذف", "Delete"),
        ["cancelSend"] = ("لغو ارسال", "Cancel sending"),
        ["fileCanceled"] = ("ارسال فایل لغو شد", "File sending canceled"),
        ["fileCanceledByPeer"] = ("ارسال فایل توسط فرستنده لغو شد", "Sender canceled the file"),
        ["noNetwork"] = ("شبکه‌ای پیدا نشد؛ به وای‌فای وصل شوید یا هات‌اسپات را روشن کنید", "No network found; join Wi-Fi or turn on hotspot"),
        ["badIp"] = ("آدرس IP معتبر نیست (مثال: 192.168.1.5)", "Invalid IP address (e.g. 192.168.1.5)"),
        ["selfIp"] = ("این آدرس مربوط به همین دستگاه است؛ IP دستگاه مقابل را وارد کنید", "That is this device's own address; enter the other device's IP"),
        ["tcpTimeout"] = ("پاسخی از دستگاه مقابل نیامد (IP یا شبکه را بررسی کنید)", "No response from the other device (check IP / network)"),
        ["tcpRefused"] = ("دستگاه پیدا شد ولی برنامه آنجا آماده نیست (برنامه را باز کنید)", "Device reached but the app isn't listening there (open the app)"),
        ["search"] = ("جستجوی دستگاه‌ها", "Find devices"),
        ["searching"] = ("در حال جستجو...", "Searching..."),
        ["noneFound"] = ("دستگاهی پیدا نشد؛ دستگاه مقابل هم باید برنامه را باز و حالت وای‌فای را انتخاب کرده باشد", "No device found; the other device must have the app open in Wi-Fi mode"),
        ["foundHeader"] = ("دستگاه‌های پیدا شده (برای اتصال بزنید):", "Devices found (tap to connect):"),
        ["showQr"] = ("نمایش QR", "Show QR"),
        ["scanQr"] = ("اسکن QR", "Scan QR"),
        ["close"] = ("بستن", "Close"),
        ["qrTitle"] = ("این QR را با دستگاه مقابل اسکن کنید", "Scan this QR with the other device"),
        ["qrScanHint"] = ("QR نمایش‌داده‌شده روی دستگاه مقابل را داخل کادر بگیرید", "Point the camera at the QR shown on the other device"),
        ["qrInvalid"] = ("این QR مربوط به BtChat نیست", "This QR code is not from BtChat"),
        ["qrNoCamera"] = ("دسترسی به دوربین داده نشد", "Camera permission denied"),
        ["qrFailed"] = ("اسکن QR انجام نشد", "QR scan failed"),
        ["queued"] = ("در صف ارسال...", "Waiting in queue..."),
        ["fileWaiting"] = ("در انتظار شروع دریافت...", "Waiting to be received..."),
        ["transferCount"] = ("{0} فایل در حال انتقال", "{0} file(s) transferring"),
        ["concurrentFiles"] = ("ارسال همزمان چند فایل", "Send several files at once"),
        ["notifChannel"] = ("اتصال BtChat", "BtChat connection"),
        ["notifConnected"] = ("متصل است؛ اتصال در پس‌زمینه نگه داشته می‌شود", "Connected; keeping the link alive in the background"),
        ["notifRetrying"] = ("در حال اتصال مجدد...", "Reconnecting..."),
        ["battery"] = ("🔋 باتری", "🔋 Battery"),
        ["batteryHint"] = ("برای اینکه اتصال و تماس‌ها وقتی برنامه در پس‌زمینه است یا صفحه خاموش شده، توسط سیستم بسته نشوند، این گزینه را باز کنید و برای برنامه «بدون محدودیت» را انتخاب کنید. در بعضی گوشی‌ها لازم است «شروع خودکار» را هم فعال کنید.", "Open this and set the app to \"Unrestricted\" so the system does not close the connection or calls when the app is in the background or the screen is off. Some phones also need Autostart enabled."),
        ["batteryAlready"] = ("اجرای بدون محدودیت باتری از قبل فعال است. اگر باز هم برنامه در پس‌زمینه بسته می‌شود، تنظیمات «شروع خودکار» یا «اجرا در پس‌زمینه» گوشی را هم بررسی کنید.", "Battery is already unrestricted. If the app is still closed in the background, also check your phone's autostart / background-run settings."),
        ["fileMissing"] = ("فایل اصلی دیگر در حافظه نیست (جابه‌جا یا پاک شده است)", "The original file is no longer on this device (moved or deleted)"),
        ["fileFailed"] = ("انتقال فایل ناموفق بود", "File transfer failed"),
        ["fileInterrupted"] = ("انتقال فایل قطع شد", "File transfer interrupted"),
        ["retry"] = ("🔄 تلاش مجدد", "🔄 Retry"),
        ["retryNeedsConnection"] = ("برای تلاش مجدد ابتدا به همان دستگاه وصل شوید", "Connect to the same device first to retry"),
        ["retryRequested"] = ("درخواست ارسال مجدد به فرستنده داده شد...", "Asked the sender to send it again..."),
        ["retryDenied"] = ("فرستنده دیگر این فایل را ندارد", "The sender no longer has this file"),
        ["pick"] = ("انتخاب دستگاه جفت‌شده", "Select paired device"),
        ["refresh"] = ("بروزرسانی", "Refresh"),
        ["connect"] = ("اتصال", "Connect"),
        ["type"] = ("پیام خود را بنویسید...", "Type a message..."),
        ["send"] = ("ارسال", "Send"),
        ["idle"] = ("متصل نیست - منتظر اتصال", "Not connected - waiting"),
        ["connecting"] = ("در حال اتصال...", "Connecting..."),
        ["connected"] = ("متصل شد", "Connected"),
        ["failed"] = ("خطا در ارتباط", "Connection error"),
        ["ip"] = ("آدرس IP دستگاه مقابل", "Other device IP address"),
        ["connectIp"] = ("اتصال با IP", "Connect via IP"),
        ["myIp"] = ("آدرس این دستگاه:", "This device:"),
        ["disconnect"] = ("قطع", "Disconnect"),
        ["retrying"] = ("در حال تلاش برای اتصال مجدد...", "Reconnecting..."),
        ["log"] = ("لاگ", "Log"),
        ["copy"] = ("کپی همه", "Copy all"),
        ["clear"] = ("پاک کردن", "Clear"),
        ["chats"] = ("چت‌ها", "Chats"),
        ["connSettings"] = ("تنظیمات اتصال", "Connection settings"),
        ["myName"] = ("نام این دستگاه", "This device's name"),
        ["myNameHint"] = ("این نام در اولین اتصال به دستگاه مقابل معرفی می‌شود و کنار پیام‌ها و پوشه فایل‌ها می‌آید", "Introduced to the other device on connect; shown beside messages and used for the files folder"),
        ["noChats"] = ("هنوز چتی نیست؛ به یک دستگاه وصل شوید تا چت آن اینجا ساخته شود", "No chats yet; connect to a device and its chat appears here"),
        ["noChatSelected"] = ("از منوی ☰ به یک دستگاه وصل شوید یا یک چت را انتخاب کنید", "Use the ☰ menu to connect to a device or pick a chat"),
        ["unknownDevice"] = ("دستگاه ناشناس", "Unknown device"),
        ["oldChat"] = ("پیام‌های قبلی", "Earlier messages"),
        ["notLinkedHere"] = ("برای ارسال پیام، به این دستگاه وصل شوید", "Connect to this device to send messages"),
        ["deleteChat"] = ("حذف چت", "Delete chat"),
        ["deleteChatAsk"] = ("این چت و همه پیام‌هایش از برنامه حذف می‌شود. فایل‌های ذخیره‌شده روی دستگاه پاک نمی‌شوند.", "This chat and all its messages will be removed from the app. Files saved on this device are not deleted."),
        ["chatInUse"] = ("چت دستگاه متصل را نمی‌توان حذف کرد؛ اول اتصال را قطع کنید", "Cannot delete the chat of the connected device; disconnect first"),
        ["permBluetoothTitle"] = ("دسترسی به بلوتوث", "Bluetooth access"),
        ["permBluetoothWhy"] = ("برای دیدن فهرست دستگاه‌های جفت‌شده و ارسال پیام و فایل به آن‌ها، برنامه به مجوز «دستگاه‌های نزدیک» (بلوتوث) نیاز دارد. برنامه دستگاه جدیدی جستجو نمی‌کند و به موقعیت مکانی شما دسترسی ندارد.", "To list your paired devices and exchange messages and files with them, the app needs the Nearby devices (Bluetooth) permission. It does not scan for new devices and does not use your location."),
        ["permCameraTitle"] = ("دسترسی به دوربین", "Camera access"),
        ["permCameraWhy"] = ("دوربین فقط برای اسکن QR دستگاه مقابل و اتصال سریع لازم است. تصویر دوربین ذخیره یا ارسال نمی‌شود.", "The camera is only used to scan the other device's QR code for a quick connection. Nothing is saved or sent."),
        ["permNotificationsTitle"] = ("نمایش اعلان", "Notifications"),
        ["permNotificationsWhy"] = ("برای اینکه اتصال در پس‌زمینه قطع نشود، برنامه یک اعلان ثابت نشان می‌دهد. این مجوز فقط برای نمایش همین اعلان است.", "To keep the connection alive in the background, the app shows one ongoing notification. This permission is only used for that notification."),
        ["permStorageTitle"] = ("دسترسی به حافظه", "Storage access"),
        ["permStorageWhy"] = ("برای ذخیره فایل‌های دریافتی در پوشه Downloads دستگاه، به دسترسی حافظه نیاز است.", "Storage access is needed to save received files into the Downloads folder."),
        ["permMicrophoneTitle"] = ("دسترسی به میکروفون", "Microphone access"),
        ["permMicrophoneWhy"] = ("میکروفون فقط وقتی که دکمه ضبط صدا را نگه می‌دارید و برای ضبط پیام صوتی استفاده می‌شود. صدای ضبط‌شده فقط برای دستگاه متصل فرستاده می‌شود و جای دیگری ارسال نمی‌شود.", "The microphone is only used while you hold the voice button, to record a voice message. The recording is sent only to the connected device, nowhere else."),
        ["permCameraCaptureTitle"] = ("دسترسی به دوربین", "Camera access"),
        ["permCameraCaptureWhy"] = ("دوربین فقط وقتی که دکمه دوربین را نگه می‌دارید و برای فیلم‌برداری استفاده می‌شود. فیلم فقط برای دستگاه متصل فرستاده می‌شود و برنامه پنهانی از دوربین استفاده نمی‌کند.", "The camera is only used when you hold the camera button, to record a video. It is sent only to the connected device, and the app never uses the camera in the background."),
        ["recordSlideCancel"] = ("برای لغو، دکمه را به کنار بکشید", "Slide to cancel"),
        ["recordReleaseCancel"] = ("رها کنید تا لغو شود", "Release to cancel"),
        ["permCallMicrophoneTitle"] = ("دسترسی به میکروفون برای تماس", "Microphone access for calls"),
        ["permCallMicrophoneWhy"] = ("برای تماس صوتی، میکروفون لازم است. صدای شما فقط در طول تماس و فقط برای دستگاه مقابل فرستاده می‌شود و ضبط یا ذخیره نمی‌شود.", "A voice call needs the microphone. Your voice is sent only during the call and only to the other device; it is never recorded or saved."),
        ["permCallCameraTitle"] = ("دسترسی به دوربین برای تماس تصویری", "Camera access for video calls"),
        ["permCallCameraWhy"] = ("برای تماس تصویری، دوربین لازم است. تصویر شما فقط در طول تماس و فقط برای دستگاه مقابل فرستاده می‌شود و ضبط یا ذخیره نمی‌شود.", "A video call needs the camera. Your picture is sent only during the call and only to the other device; it is never recorded or saved."),
        ["callVideoIncoming"] = ("تماس تصویری ورودی", "Incoming video call"),
        ["videoNeedsWifi"] = ("تماس تصویری فقط روی وای‌فای کار می‌کند؛ اتصال را روی Wi-Fi / IP برقرار کنید", "Video calls only work over Wi-Fi; connect with Wi-Fi / IP"),
        ["callChannel"] = ("تماس ورودی", "Incoming calls"),
        ["callCalling"] = ("در حال تماس...", "Calling..."),
        ["callIncoming"] = ("تماس صوتی ورودی", "Incoming voice call"),
        ["callDeclined"] = ("تماس رد شد", "Call declined"),
        ["callBusy"] = ("دستگاه مقابل در تماس است یا از تماس پشتیبانی نمی‌کند", "The other device is busy or does not support calls"),
        ["callMissed"] = ("پاسخی داده نشد", "No answer"),
        ["videoQuality"] = ("کیفیت تصویر ارسالی", "Outgoing video quality"),
        ["videoQ0"] = ("کم (مصرف کمتر، پایدارترین)", "Low (lightest, most stable)"),
        ["videoQ1"] = ("متوسط (پیشنهادی)", "Medium (recommended)"),
        ["videoQ2"] = ("بالا", "High"),
        ["videoQ3"] = ("خیلی بالا (HD، نیاز به وای‌فای قوی)", "Very high (HD, needs strong Wi-Fi)"),
        ["callMenuCamera"] = ("دوربین", "Camera"),
        ["callMenuFlip"] = ("چرخاندن", "Flip"),
        ["callMenuQuality"] = ("کیفیت", "Quality"),
        ["callMenuSpeaker"] = ("بلندگو", "Speaker"),
        ["callFailed"] = ("تماس برقرار نشد", "Could not start the call"),
        ["audioSpeed"] = ("سرعت پخش", "Playback speed"),
        ["playFailed"] = ("پخش فایل صوتی انجام نشد", "Could not play the audio"),
        ["recordFailed"] = ("ضبط صدا شروع نشد", "Could not start recording"),
        ["captureFailed"] = ("دوربین باز نشد یا فیلم ذخیره نشد", "Could not open the camera or save the video"),
        ["permContinue"] = ("ادامه", "Continue"),
        ["permNotNow"] = ("الان نه", "Not now"),
        ["permBlocked"] = ("این مجوز قبلاً رد شده و سیستم اجازه درخواست دوباره را نمی‌دهد. برای فعال کردن آن، تنظیمات برنامه را باز کنید و مجوز را روشن کنید.", "This permission was denied and the system will not ask again. Open the app settings and turn it on."),
        ["permOpenSettings"] = ("باز کردن تنظیمات", "Open settings"),
        ["btNoPermission"] = ("برای استفاده از بلوتوث مجوز لازم است؛ دکمه «بروزرسانی» را بزنید", "Bluetooth permission is needed; tap Refresh"),
        ["btTurnOnTitle"] = ("بلوتوث خاموش است", "Bluetooth is off"),
        ["btTurnOnAsk"] = ("برای اتصال باید بلوتوث روشن باشد. روشن شود؟", "Bluetooth must be on to connect. Turn it on?"),
        ["btTurnOn"] = ("روشن کردن", "Turn on"),
        ["viewImage"] = ("نمایش تصویر", "View image"),
        ["shareTo"] = ("ارسال به…", "Send to…"),
        ["shareFiles"] = ("{0} فایل", "{0} files"),
        ["shareConnectedTag"] = ("● متصل", "● Connected"),
        ["shareNoChats"] = ("هنوز گفتگویی وجود ندارد. ابتدا به یک دستگاه وصل شوید.", "No chats yet. Connect to a device first."),
        ["shareCopying"] = ("در حال آماده‌سازی فایل...", "Preparing the file..."),
        ["fileNotSent"] = ("هنوز ارسال نشده؛ پس از اتصال دکمه‌ی تلاش مجدد را بزنید", "Not sent yet - press Retry once connected"),
        ["connection"] = ("اتصال", "Connection"),
        ["connectedTo"] = ("متصل به {0}", "Connected to {0}"),
        ["easyConnect"] = ("اتصال آسان", "Easy connect"),
        ["tileSearch"] = ("جستجوی دستگاه‌ها در شبکه", "Find devices on the network"),
        ["tileSearchHint"] = ("دستگاه مقابل هم برنامه را باز کرده باشد", "The other device must have the app open"),
        ["manualConnect"] = ("اتصال دستی", "Manual connection"),
        ["manualHint"] = ("آدرس IP دستگاه مقابل را بنویسید. همان را در «اتصال دستی» دستگاه مقابل زیر «آدرس این دستگاه» می‌بینید.", "Type the other device's IP address. You can read it under This device in its Manual connection section."),
        ["settings"] = ("تنظیمات", "Settings"),
        ["setProfile"] = ("پروفایل", "Profile"),
        ["setAppearance"] = ("ظاهر", "Appearance"),
        ["setLanguage"] = ("زبان", "Language"),
        ["setTheme"] = ("پوسته", "Theme"),
        ["themeAuto"] = ("خودکار", "Auto"),
        ["themeLight"] = ("روشن", "Light"),
        ["themeDark"] = ("تیره", "Dark"),
        ["setTransfer"] = ("انتقال فایل", "File transfer"),
        ["concurrentFilesHint"] = ("در Wi-Fi چند فایل هم‌زمان فرستاده می‌شود. روی بلوتوث همیشه یکی‌یکی.", "On Wi-Fi several files are sent at once. Bluetooth always sends one by one."),
        ["setAdvanced"] = ("پیشرفته", "Advanced"),
        ["setAbout"] = ("درباره", "About"),
        ["securing"] = ("در حال برقراری ارتباط امن...", "Setting up a secure link..."),
        ["secUnsupported"] = ("دستگاه مقابل نسخهٔ قدیمی برنامه را دارد؛ برنامه را روی هر دو دستگاه به‌روز کنید", "The other device runs an older version; update the app on both devices"),
        ["secFailed"] = ("برقراری ارتباط امن انجام نشد", "Could not set up the secure link"),
        ["secCancelled"] = ("اتصال لغو شد (تنظیم رمزنگاری دو دستگاه یکسان نیست)", "Connection canceled (the two devices have different encryption settings)"),
        ["secPeerCancelled"] = ("دستگاه مقابل اتصال را لغو کرد (تنظیم رمزنگاری یکسان نیست)", "The other device canceled the connection (encryption settings differ)"),
        ["secTitle"] = ("رمزنگاری", "Encryption"),
        ["secMismatchOff"] = ("رمزنگاری روی دستگاه مقابل روشن است، ولی روی این دستگاه خاموش است", "Encryption is on at the other device but off here"),
        ["secMismatchOn"] = ("رمزنگاری روی این دستگاه روشن است، ولی دستگاه مقابل بدون رمزنگاری ادامه می‌دهد. بدون رمزنگاری وصل شویم؟", "Encryption is on here, but the other device wants to continue without it. Connect without encryption?"),
        ["secEnable"] = ("روشن کردن رمزنگاری", "Turn on encryption"),
        ["secContinuePlain"] = ("ادامه بدون رمزنگاری", "Continue without encryption"),
        ["setSecurity"] = ("امنیت", "Security"),
        ["encrypt"] = ("رمزنگاری پیام‌ها و فایل‌ها", "Encrypt messages and files"),
        ["encryptHint"] = ("پیام‌ها و فایل‌ها بین دو دستگاه رمز می‌شوند تا کسی در مسیر نتواند آن‌ها را بخواند. روی هر دو دستگاه باید روشن باشد. به‌طور پیش‌فرض خاموش است چون کمی از سرعت می‌کاهد.", "Messages and files are encrypted between the two devices so nobody on the way can read them. It must be on at both devices. Off by default because it can slow transfers a little."),
        ["encryptHintNext"] = ("تغییر از اتصال بعدی اعمال می‌شود.", "The change applies from the next connection."),
        ["verifyPeers"] = ("تأیید هویت دستگاه‌ها", "Verify devices"),
        ["verifyPeersHint"] = ("اگر QR دستگاه مقابل اثر انگشت کلیدش را داشته باشد، هنگام اسکن بررسی می‌شود؛ و اگر کلید دستگاهی که قبلاً می‌شناختی عوض شود هشدار می‌دهد. فقط وقتی رمزنگاری روشن است کار می‌کند. به‌طور پیش‌فرض خاموش است.", "When the other device's QR code carries its key fingerprint it is checked on scan, and you get a warning if the key of a device you already know changes. Works only while encryption is on. Off by default."),
        ["myFingerprint"] = ("اثر انگشت این دستگاه", "This device's fingerprint"),
        ["secWrongDevice"] = ("اتصال لغو شد: دستگاه مقابل با QR اسکن‌شده یکی نیست", "Connection canceled: the other device does not match the scanned QR code"),
        ["secNotVerified"] = ("اتصال لغو شد: بدون رمزنگاری نمی‌شود هویت دستگاه مقابل را با QR تأیید کرد", "Connection canceled: without encryption the device can not be checked against the QR code"),
        ["secKeyRejected"] = ("اتصال لغو شد: کلید امنیتی دستگاه مقابل تغییر کرده بود", "Connection canceled: the other device's security key had changed"),
        ["secKeyChangedTitle"] = ("کلید امنیتی تغییر کرده", "Security key changed"),
        ["secKeyChanged"] = ("کلید امنیتی «{0}» با دفعهٔ قبل فرق دارد. ممکن است برنامه روی آن دستگاه دوباره نصب شده باشد، یا کس دیگری خودش را جای آن جا زده باشد. اگر مطمئن نیستی لغو کن. به کلید جدید اعتماد شود؟", "The security key of \"{0}\" is different from last time. The app may have been reinstalled there, or someone else may be pretending to be that device. Cancel if you are not sure. Trust the new key?"),
        ["secTrust"] = ("اعتماد و ادامه", "Trust and continue"),
        ["proxyAdvanced"] = ("تنظیمات پیشرفته", "Advanced settings"),
        ["reply"] = ("↩ پاسخ", "↩ Reply"),
        ["replyTo"] = ("پاسخ به {0}", "Reply to {0}"),
        ["pin"] = ("📌 پین کردن", "📌 Pin"),
        ["unpin"] = ("برداشتن پین", "Unpin"),
        ["pinnedMessage"] = ("پیام پین‌شده", "Pinned message"),
        ["winDownload"] = ("💻 دانلود نسخه ویندوز", "💻 Download Windows version"),
        ["winDownloadHint"] = ("صفحهٔ پروژه در GitHub باز می‌شود؛ نسخهٔ ویندوز را از همان‌جا دانلود کنید.", "Opens the project page on GitHub, where you can download the Windows version."),
        ["openLinkFailed"] = ("باز کردن لینک انجام نشد", "Could not open the link"),
        ["version"] = ("نسخه", "Version"),
        ["speed"] = ("سرعت پخش", "Playback speed"),
        ["subtitles"] = ("زیرنویس", "Subtitles"),
        ["subtitleChoose"] = ("انتخاب فایل زیرنویس (SRT / VTT)", "Choose subtitle file (SRT / VTT)"),
        ["subtitleOff"] = ("خاموش کردن زیرنویس", "Turn subtitles off"),
        ["subtitleEarlier"] = ("زیرنویس زودتر نمایش داده شود (−۰٫۵ ثانیه)", "Show subtitles earlier (−0.5 s)"),
        ["subtitleLater"] = ("زیرنویس دیرتر نمایش داده شود (+۰٫۵ ثانیه)", "Show subtitles later (+0.5 s)"),
        ["subtitleBigger"] = ("بزرگ‌تر کردن متن زیرنویس", "Bigger subtitle text"),
        ["subtitleSmaller"] = ("کوچک‌تر کردن متن زیرنویس", "Smaller subtitle text"),
        ["subtitleFailed"] = ("خواندن زیرنویس ممکن نشد (فقط SRT و VTT)", "Could not read the subtitles (SRT and VTT only)"),
        ["playFailed"] = ("این فایل در پخش‌کننده‌ی داخلی باز نشد. با دکمه‌ی ↗ با برنامه‌ی دیگری باز کنید.", "This file could not be played here. Use the ↗ button to open it in another app."),
        ["playMedia"] = ("پخش در برنامه", "Play in app"),
        ["openWith"] = ("باز کردن با برنامه‌های دیگر", "Open with another app"),
        ["renameChat"] = ("تغییر نام چت", "Rename chat"),
        ["renameChatAsk"] = ("نام جدید چت (خالی = نام خود دستگاه). پوشه فایل‌های بعدی هم با همین نام ساخته می‌شود.", "New chat name (empty = the device's own name). New files go to a folder with this name."),
        ["save"] = ("ذخیره", "Save"),
        ["logTitle"] = ("گزارش (لاگ)", "Log"),
        ["secShort"] = ("ثانیه", "s"),
        ["minShort"] = ("دقیقه", "min"),
        ["ok"] = ("باشه", "OK"),
        ["helpBluetoothTitle"] = ("اتصال با بلوتوث", "Connect with Bluetooth"),
        ["helpBluetooth"] = (
            "۱. بلوتوث هر دو دستگاه را روشن کنید.\n\n۲. دو دستگاه را با هم «جفت» (Pair) کنید. در گوشی: تنظیمات ‹ بلوتوث. در ویندوز: Settings ‹ Bluetooth & devices ‹ Add device. کد نمایش‌داده‌شده را روی هر دو تأیید کنید. این کار فقط یک بار لازم است.\n\n۳. برنامه را روی هر دو دستگاه باز کنید.\n\n۴. در این کشو «نوع اتصال» را روی بلوتوث بگذارید، نام دستگاه مقابل را از «انتخاب دستگاه جفت‌شده» بردارید (اگر در لیست نبود «بروزرسانی» را بزنید) و دکمه «اتصال» را بزنید. کافی است اتصال را فقط روی یکی از دو دستگاه بزنید.\n\n۵. بعد از اتصال، دو دستگاه خودشان را به هم معرفی می‌کنند و چتی با نام دستگاه مقابل ساخته می‌شود.\n\nاگر ارتباط قطع شود، برنامه خودش دوباره تلاش می‌کند.",
            "1. Turn Bluetooth on for both devices.\n\n2. Pair the two devices. On a phone: Settings > Bluetooth. On Windows: Settings > Bluetooth & devices > Add device. Confirm the code on both. This is needed only once.\n\n3. Open the app on both devices.\n\n4. In this drawer set the connection type to Bluetooth, pick the other device under Select paired device (tap Refresh if it is missing) and press Connect. Pressing Connect on just one of the two devices is enough.\n\n5. After connecting, the devices introduce themselves and a chat with the other device's name is created.\n\nIf the link drops, the app retries by itself."),
        ["helpWifiTitle"] = ("اتصال با وای‌فای / هات‌اسپات", "Connect with Wi-Fi / hotspot"),
        ["helpWifi"] = (
            "۱. هر دو دستگاه باید در یک شبکه باشند: یا هر دو به یک وای‌فای وصل شوند، یا یکی از آن‌ها هات‌اسپات (Hotspot) روشن کند و دیگری به آن وصل شود. اینترنت لازم نیست.\n\n۲. برنامه را روی هر دو دستگاه باز کنید و «نوع اتصال» را روی Wi-Fi / IP بگذارید.\n\n۳. یکی از این راه‌ها را انتخاب کنید:\n• «جستجوی دستگاه‌ها» و لمس نام دستگاه مقابل (ساده‌ترین راه)\n• «نمایش QR» روی یک دستگاه و «اسکن QR» روی گوشی دیگر\n• نوشتن IP دستگاه مقابل در بخش «اتصال دستی»\n\n۴. اگر ویندوز پیام فایروال نشان داد، اجازه دسترسی در شبکه خصوصی (Private) را بدهید.\n\n۵. بعد از اتصال دو دستگاه یکدیگر را معرفی می‌کنند. بلوتوث و وای‌فای یک دستگاه در همان یک چت قرار می‌گیرند.",
            "1. Both devices must be on the same network: either join the same Wi-Fi, or let one device turn on its hotspot and the other join it. Internet is not needed.\n\n2. Open the app on both devices and set the connection type to Wi-Fi / IP.\n\n3. Pick one way:\n• Find devices, then tap the other device's name (easiest)\n• Show QR on one device and Scan QR on the other phone\n• Type the other device's IP address in Manual connection\n\n4. If Windows shows a firewall prompt, allow access on Private networks.\n\n5. After connecting, the devices introduce themselves. Bluetooth and Wi-Fi of the same device share one chat."),
        ["helpIpTitle"] = ("اتصال با آدرس IP", "Connect by IP address"),
        ["helpIp"] = (
            "۱. روی دستگاه مقابل در کشوی کناری، بخش «اتصال دستی» را باز کنید و در خط «آدرس این دستگاه» آدرس را ببینید (مثل 192.168.1.5). اگر خالی بود «بروزرسانی» را بزنید.\n\n۲. همان آدرس را اینجا بنویسید و «اتصال با IP» را بزنید.\n\n۳. هر دو دستگاه باید در یک شبکه باشند. اگر دستگاه مقابل چند آدرس نشان داد، آدرسی را امتحان کنید که شروعش شبیه آدرس دستگاه شماست.\n\n۴. آدرس خود دستگاه را وارد نکنید.",
            "1. On the other device open the Manual connection section in the side drawer and read the address in the This device line (like 192.168.1.5). Tap Refresh if it is empty.\n\n2. Type that address here and press Connect via IP.\n\n3. Both devices must be on the same network. If the other device shows several addresses, try the one that starts like your own device's address.\n\n4. Do not enter this device's own address."),
        ["helpQuickTitle"] = ("جستجو و QR", "Search and QR"),
        ["helpQuick"] = (
            "جستجوی دستگاه‌ها:\nدستگاه مقابل هم باید برنامه را باز کرده و حالت Wi-Fi / IP را انتخاب کرده باشد. بعد از جستجو نامش در لیست می‌آید و با لمس آن وصل می‌شوید.\n\nQR:\nروی یکی از دو دستگاه «نمایش QR» را بزنید و روی گوشی اندروید دیگر «اسکن QR» را بزنید و دوربین را روی کد بگیرید. اتصال خودکار برقرار می‌شود و نیازی به نوشتن IP نیست.\n\nنکته: ویندوز فقط می‌تواند QR را نمایش دهد؛ اسکن با گوشی اندروید انجام می‌شود. اولین بار اجازه دوربین پرسیده می‌شود.",
            "Find devices:\nThe other device must have the app open in Wi-Fi / IP mode. After the search its name appears in the list; tap it to connect.\n\nQR:\nPress Show QR on one device and Scan QR on the other Android phone, then point the camera at the code. It connects automatically, no IP typing needed.\n\nNote: Windows can only show the QR; scanning is done with an Android phone. The camera permission is asked the first time."),
        ["proxyTitle"] = ("اشتراک اینترنت / پروکسی", "Internet sharing / Proxy"),
        ["proxyDrawerHint"] = ("اینترنت یک دستگاه روی دستگاه دیگر پروکسی می‌شود", "One device's internet is proxied on another device"),
        ["proxyIntro"] = ("اینترنت یک دستگاه روی دستگاه دیگر پروکسی می‌شود", "One device's internet is proxied on another device"),
        ["proxyStart"] = ("شروع اشتراک", "Start sharing"),
        ["proxyStop"] = ("توقف اشتراک", "Stop sharing"),
        ["proxyStatusRunning"] = ("روشن · پورت {0} · {1} دستگاه", "On · port {0} · {1} devices"),
        ["proxyNotif"] = ("اشتراک اینترنت روشن است (پورت {0})", "Internet sharing is on (port {0})"),
        ["proxyKindDirect"] = ("مستقیم", "Direct"),
        ["proxyKindReverse"] = ("اتصال معکوس", "Reverse connection"),
        ["proxyReverseHint"] = ("این دستگاه خودش به دستگاه گیرنده وصل می‌شود. در دستگاه دیگر «دریافت اتصال معکوس» را روشن کنید.", "This device connects out to the receiving device. On the other device turn on Receive reverse connection."),
        ["proxyReverseHost"] = ("آدرس دستگاه گیرنده", "Receiver address"),
        ["proxyReversePort"] = ("پورت اتصال دستگاه گیرنده", "Receiver link port"),
        ["proxyPairPass"] = ("رمز جفت‌شدن (اختیاری)", "Pairing password (optional)"),
        ["proxyScanReceiver"] = ("اسکن QR دستگاه گیرنده", "Scan the receiver's QR"),
        ["proxyNeedReceiver"] = ("آدرس دستگاه گیرنده را وارد کنید", "Enter the receiver's address"),
        ["proxyStatusReverse"] = ("روشن · وصل به {0} · آماده: {1}", "On · linked to {0} · ready: {1}"),
        ["proxyNotifReverse"] = ("اشتراک اینترنت روشن است (اتصال به {0})", "Internet sharing is on (linked to {0})"),
        ["pcKindConnect"] = ("اتصال به پروکسی", "Connect to proxy"),
        ["pcKindReceive"] = ("دریافت اتصال معکوس", "Receive reverse connection"),
        ["rvIntro"] = ("دستگاهی که اینترنت دارد باید در حالت «اتصال معکوس» به یکی از این آدرس‌ها وصل شود.", "The sharing device, in Reverse connection mode, connects to one of these addresses."),
        ["rvStart"] = ("شروع دریافت", "Start receiving"),
        ["rvStop"] = ("توقف دریافت", "Stop receiving"),
        ["rvLinkAddress"] = ("آدرس اتصال (برای دستگاه دیگر)", "Link address (for the other device)"),
        ["rvLinkPort"] = ("پورت اتصال", "Link port"),
        ["rvLocalPort"] = ("پورت پروکسی روی این دستگاه", "Proxy port on this device"),
        ["rvLocalProxy"] = ("پروکسی این دستگاه: {0}", "Proxy on this device: {0}"),
        ["rvSamePort"] = ("پورت اتصال و پورت پروکسی نباید یکی باشند", "The link port and the proxy port must differ"),
        ["rvWaiting"] = ("منتظر اتصال دستگاه دیگر…", "Waiting for the other device…"),
        ["rvLinked"] = ("دستگاه دیگر وصل است", "The other device is linked"),
        ["rvNoLink"] = ("هنوز هیچ دستگاهی وصل نشده است", "No device is linked yet"),
        ["rvStats"] = ("آماده: {0}   اتصال‌های باز: {1}   دانلود: {2}   آپلود: {3}", "Ready: {0}   Open: {1}   Down: {2}   Up: {3}"),
        ["rvNotif"] = ("دریافت اتصال روشن است (پورت {0})", "Receiving is on (port {0})"),
        ["rvStatusRunning"] = ("روشن · پورت اتصال {0} · پروکسی {1}", "On · link port {0} · proxy {1}"),
        ["proxyAddress"] = ("آدرس پروکسی", "Proxy address"),
        ["proxyTapCopy"] = ("برای کپی، آدرس را لمس کنید", "Tap an address to copy it"),
        ["proxyCopied"] = ("کپی شد", "Copied"),
        ["proxyStats"] = ("آمار زنده", "Live statistics"),
        ["proxyStatConn"] = ("اتصال‌ها", "Connections"),
        ["proxyStatDevices"] = ("دستگاه‌ها", "Devices"),
        ["proxyStatDown"] = ("دانلود", "Download"),
        ["proxyStatUp"] = ("آپلود", "Upload"),
        ["proxyStatTotalDown"] = ("کل دانلود", "Total download"),
        ["proxyStatTotalUp"] = ("کل آپلود", "Total upload"),
        ["proxyCapUsed"] = ("مصرف: {0} از {1}", "Used {0} of {1}"),
        ["proxyLimitReached"] = ("به سقف حجم رسید و اشتراک متوقف شد. شمارنده‌ها را صفر کنید یا سقف را بالاتر ببرید.", "The data cap was reached and sharing is paused. Reset the counters or raise the cap."),
        ["proxyClientLimit"] = ("به سقف رسید", "Cap reached"),
        ["proxyClientDetail"] = ("{0} اتصال · ↓{1} ↑{2}", "{0} conn · ↓{1} ↑{2}"),
        ["proxyResetCounters"] = ("صفر کردن شمارنده‌ها", "Reset counters"),
        ["proxyClients"] = ("دستگاه‌های متصل", "Connected devices"),
        ["proxyServerSettings"] = ("تنظیمات سرور", "Server settings"),
        ["proxyStopToEdit"] = ("برای تغییر پورت و امنیت، اول اشتراک را متوقف کنید", "Stop sharing to change the port and security"),
        ["proxyPort"] = ("پورت", "Port"),
        ["proxyPortHint"] = ("پیش‌فرض ۸۰۸۰", "Default 8080"),
        ["proxyAuth"] = ("نام کاربری و رمز عبور", "User name and password"),
        ["proxyAuthHint"] = ("اختیاری. اگر خاموش باشد، هر دستگاهِ شبکه محلی می‌تواند وصل شود.", "Optional. When off, any device on the local network can connect."),
        ["proxyUser"] = ("نام کاربری", "User name"),
        ["proxyPass"] = ("رمز عبور", "Password"),
        ["proxyLocalOnly"] = ("فقط شبکه محلی", "Local network only"),
        ["proxyLocalOnlyHint"] = ("فقط دستگاه‌هایی که روی همین هات‌اسپات یا وای‌فای هستند اجازه اتصال دارند.", "Only devices on this hotspot or local network may connect."),
        ["proxyLimitTotal"] = ("سقف حجم کل (همه دستگاه‌ها)", "Total data cap (all devices)"),
        ["proxyLimitClient"] = ("سقف حجم هر دستگاه", "Data cap per device"),
        ["proxyUnlimited"] = ("نامحدود", "Unlimited"),
        ["proxyLimitHint"] = ("خالی = نامحدود. سقف‌ها را می‌شود هنگام اشتراک هم تغییر داد.", "Empty = unlimited. The caps can also be changed while sharing."),
        ["proxyBadPort"] = ("پورت باید عددی بین ۱ تا ۶۵۵۳۵ باشد", "The port must be a number from 1 to 65535"),
        ["proxyNeedCreds"] = ("نام کاربری و رمز عبور را وارد کنید", "Enter a user name and a password"),
        ["proxyBadUser"] = ("نام کاربری نباید «:» داشته باشد", "The user name must not contain ':'"),
        ["proxyBadLimit"] = ("سقف حجم باید یک عدد مثبت باشد (یا خالی)", "The data cap must be a positive number (or empty)"),
        ["proxyPortBusy"] = ("پورت {0} در حال استفاده است؛ پورت دیگری انتخاب کنید", "Port {0} is already in use; pick another port"),
        ["proxyPortDenied"] = ("اجازه استفاده از پورت {0} داده نشد؛ پورتی بالای ۱۰۲۴ انتخاب کنید", "Not allowed to use port {0}; pick a port above 1024"),
        ["proxyStartFailed"] = ("شروع پروکسی ناموفق بود: {0}", "Could not start the proxy: {0}"),
        ["proxyQrIncludePass"] = ("نام کاربری و رمز عبور هم داخل QR باشد؟ هر کس این QR را اسکن کند رمز را می‌بیند.", "Put the user name and password in the QR code too? Anyone who scans it will see them."),
        ["proxyQrInclude"] = ("بله، شامل شود", "Yes, include"),
        ["proxyQrWithout"] = ("نه، بدون رمز", "No, without"),
        ["helpProxyTitle"] = ("اشتراک اینترنت / پروکسی", "Internet sharing / proxy"),
        ["helpProxy"] = (
            "۱. هات‌اسپات یا وای‌فای را وصل کنید.\n۲. «شروع اشتراک» را بزنید.\n۳. روی دستگاه دیگر در تنظیمات وای‌فای، پروکسی را «دستی» کنید و آدرس و پورت را وارد کنید. در ویندوز: تنظیمات ← شبکه ← پروکسی.\n\nنکته‌ها:\n• نوع پروکسی HTTP یا SOCKS5 است (هر دو روی یک پورت).\n• UDP (بعضی بازی‌ها و تماس‌ها) پشتیبانی نمی‌شود.\n• ویندوز: بار اول فایروال اجازه می‌خواهد؛ Allow را بزنید.\n\nاتصال معکوس (اگر مستقیم کار نکرد):\n۱. روی دستگاه گیرنده «دریافت اتصال معکوس» را شروع کنید.\n۲. روی دستگاه دارای اینترنت «اتصال معکوس» را انتخاب کنید، آدرس گیرنده را وارد یا QR را اسکن کنید و «شروع اشتراک» را بزنید.\n۳. پروکسی روی دستگاه گیرنده در 127.0.0.1 ساخته می‌شود.",
            "1. Connect the hotspot or Wi-Fi.\n2. Tap Start sharing.\n3. On the other device set the Wi-Fi proxy to Manual and enter the address and port. On Windows: Settings > Network > Proxy.\n\nNotes:\n• The proxy type is HTTP or SOCKS5 (both on the same port).\n• UDP (some games and calls) is not supported.\n• Windows asks the firewall for permission the first time; choose Allow.\n\nReverse connection (if direct does not work):\n1. On the receiving device start Receive reverse connection.\n2. On the device with the internet choose Reverse connection, enter the receiver address or scan its QR, and tap Start sharing.\n3. The proxy on the receiving device is at 127.0.0.1."),
        ["proxyModeServer"] = ("سرور", "Server"),
        ["proxyModeClient"] = ("کلاینت", "Client"),
        ["pcIntro"] = ("اینترنت یک دستگاه روی دستگاه دیگر پروکسی می‌شود", "One device's internet is proxied on another device"),
        ["pcScanQr"] = ("اسکن QR سرور", "Scan the server's QR"),
        ["pcScanQrHint"] = ("آدرس، پورت و رمز خودکار پر می‌شود", "Fills in the address, port and password for you"),
        ["pcManual"] = ("اتصال دستی", "Manual connection"),
        ["pcHost"] = ("آدرس سرور (IP)", "Server address (IP)"),
        ["pcAuthLabel"] = ("نام کاربری و رمز (اگر سرور رمز دارد)", "User name and password (if the server has one)"),
        ["pcTest"] = ("تست اتصال", "Test connection"),
        ["pcTesting"] = ("در حال تست...", "Testing..."),
        ["pcOk"] = ("وصل است؛ اینترنت از طریق پروکسی در دسترس است ({0} میلی‌ثانیه)", "Connected; the internet is reachable through the proxy ({0} ms)"),
        ["pcUnreachable"] = ("به {0}:{1} وصل نشد. آدرس را بررسی کنید و مطمئن شوید هر دو دستگاه در یک شبکه‌اند و اشتراک روشن است.", "Cannot reach {0}:{1}. Check the address, that both devices are on the same network and that sharing is on."),
        ["pcTimeout"] = ("پروکسی به موقع پاسخ نداد", "The proxy did not answer in time"),
        ["pcRejected"] = ("سرور ارتباط را بست؛ شاید این دستگاه مجاز نیست یا سقف حجم تمام شده است", "The server closed the connection; this device may not be allowed or the data cap is used up"),
        ["pcAuth"] = ("نام کاربری یا رمز عبور اشتباه است (یا سرور رمز می‌خواهد)", "Wrong user name or password (or the server needs one)"),
        ["pcTargetRefused"] = ("پروکسی جواب می‌دهد ولی به اینترنت نرسید. ({0})", "The proxy answers but could not reach the internet. ({0})"),
        ["pcNotProxy"] = ("این آدرس یک پروکسی BtChat / SOCKS5 نیست", "That address is not a BtChat / SOCKS5 proxy"),
        ["pcError"] = ("خطا: {0}", "Error: {0}"),
        ["pcNeedHost"] = ("آدرس سرور را وارد کنید", "Enter the server address"),
        ["pcQrInvalid"] = ("این QR مربوط به اشتراک اینترنت نیست", "This QR is not an internet sharing code"),
        ["pcUse"] = ("استفاده روی این دستگاه", "Use on this device"),
        ["pcSystemHint"] = ("با روشن کردن این گزینه، پروکسی سیستم ویندوز تنظیم می‌شود و مرورگر و بیشتر برنامه‌ها از آن استفاده می‌کنند. با خاموش کردن یا بستن برنامه، تنظیمات قبلی برمی‌گردد.", "This sets the Windows system proxy, so browsers and most apps use it. Your previous settings come back when you turn it off or close the app."),
        ["pcSystemOn"] = ("استفاده به عنوان پروکسی سیستم", "Use as system proxy"),
        ["pcSystemOff"] = ("قطع پروکسی سیستم", "Stop using the system proxy"),
        ["pcSystemActive"] = ("پروکسی سیستم تنظیم شد: {0}:{1}", "System proxy set: {0}:{1}"),
        ["pcSystemAuthNote"] = ("این سرور رمز دارد؛ برنامه‌ها نام کاربری و رمز را می‌پرسند.", "This server has a password; apps will ask for the user name and password."),
        ["pcSystemRestored"] = ("تنظیمات قبلی پروکسی برگشت", "Your previous proxy settings were restored"),
        ["pcSystemFailed"] = ("تنظیم پروکسی سیستم ناموفق بود: {0}", "Could not set the system proxy: {0}"),
        ["pcManualHint"] = (
            "در تنظیمات وای‌فای گوشی: روی شبکه فعلی بزنید ← پروکسی ← دستی، و آدرس و پورت بالا را وارد کنید.\n\nنکته: پروکسی وای‌فای اندروید جای رمز ندارد؛ مرورگر معمولاً رمز را می‌پرسد ولی بعضی برنامه‌ها نمی‌توانند از پروکسی رمزدار استفاده کنند.",
            "In the phone's Wi-Fi settings: tap the current network > Proxy > Manual, then enter the address and port above.\n\nNote: Android's Wi-Fi proxy has no password field; browsers usually ask for it, but some apps cannot use a password-protected proxy."),
        ["pcCopyAddress"] = ("کپی آدرس و پورت", "Copy address and port"),
        ["pcOpenWifi"] = ("باز کردن تنظیمات وای‌فای", "Open Wi-Fi settings"),
        ["pcVpnHint"] = ("اینترنت یک دستگاه روی دستگاه دیگر پروکسی می‌شود", "One device's internet is proxied on another device"),
        ["pcVpnOn"] = ("روشن کردن (همه برنامه‌ها)", "Start (all apps)"),
        ["pcVpnOff"] = ("خاموش کردن", "Stop"),
        ["pcVpnStarted"] = ("روشن شد؛ همه برنامه‌ها از اینترنت سرور استفاده می‌کنند", "Started; all apps now use the server's internet"),
        ["pcVpnStopped"] = ("خاموش شد", "Stopped"),
        ["pcVpnDenied"] = ("اجازه داده نشد", "Permission was not granted"),
        ["pcVpnFailed"] = ("روشن نشد: {0}", "Could not start: {0}"),
        ["pcVpnStats"] = ("دانلود: {0}   آپلود: {1}   اتصال‌های باز: {2}", "Down: {0}   Up: {1}   Open connections: {2}"),
        ["vpnNotifChannel"] = ("اشتراک اینترنت", "Internet sharing"),
        ["vpnNotifTitle"] = ("BtChat روشن است", "BtChat is on"),
        ["vpnNotifStop"] = ("خاموش کردن", "Turn off"),
        ["btoff"] = ("بلوتوث خاموش است یا دسترسی داده نشده", "Bluetooth is off or permission denied")
    };

    public bool IsFa { get; private set; } = SavedLanguageIsFa();

    // The language chosen in the first-run dialog or in Settings is remembered; until then it is English.
    public static bool HasSavedLanguage
    {
        get
        {
            try
            {
                return Preferences.Default.Get("lang", "") is "fa" or "en";
            }
            catch
            {
                return false;
            }
        }
    }

    public void SaveChoice()
    {
        try { Preferences.Default.Set("lang", IsFa ? "fa" : "en"); } catch { }
    }

    static bool SavedLanguageIsFa()
    {
        try
        {
            var saved = Preferences.Default.Get("lang", "");
            if (saved == "fa") return true;
            if (saved == "en") return false;
        }
        catch
        {
        }
        return false;
    }

    public string this[string key] => table.TryGetValue(key, out var v) ? (IsFa ? v.Fa : v.En) : key;

    public FlowDirection Flow => IsFa ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

    public event PropertyChangedEventHandler? PropertyChanged;

    public void Toggle()
    {
        IsFa = !IsFa;
        SaveChoice();
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
    }
}
